#!/bin/bash

# Say hello
echo -e "\nDHCP-Discover\n"
echo -e "Power on your new network node."
echo -e "Give it a new DHCP-lease."

# Check if root
if [ "$EUID" -ne 0 ]
  then echo -e "\nPlease run as root!\n"
  exit 1
fi

# Specify network interface
if [[ $# -ne 1 ]] ; then
    echo -e '\nPlease specify network interface as parameter (e.g. eth0).\n'
    exit 1
fi

# Check if this computer's network interface is up
nicisup=`ip a | sed -rn '/: '"$1"':.*state UP/{N;N;s/.*inet (\S*).*/\1/p}'`
if [ "$nicisup" == "" ]; then
    echo -e "\nYour network interface is down or unavailable.\n"
    exit 1
fi

# Check if tcpdump is available
if ! command -v tcpdump &> /dev/null
then
    echo -e "\ntcpdump could not be found.\n"
    exit 1
fi

# Good to go ...
echo -e "\nListening to $1 ...\n"

# Infinite loop starts here ---
#while true
#do

# Find a solution to suppress tcpdump output

#tcpdump -i $1 -n port 67 and port 68 -c 1 | grep -i BOOT
#tcpdump -i $1 -n port 67 and port 68 2>&1 | grep BOOTP
#https://stackoverflow.com/questions/34496462/append-output-of-grep-filter-to-a-file !? geht nicht
#http://xed.ch/help/tcpdump.html
#Muting tcpdump: https://stackoverflow.com/questions/7686989/running-bash-commands-in-the-background-without-printing-job-and-process-ids TODO !!!
#?!?!?!!??

echo -e "Running tcpdump on port 67 and 68 (DHCP/BOOTP)\n"

# Run tcpdump and write mac-address of new device to file
tcpdump -i $1 -n port 67 and port 68 -c 1 | tee mac.tmp
mac=`cat mac.tmp | awk {'print $9'} | sed 's/.$//'`

# Get IP from arp -a
ip=`arp -a | grep $mac |  awk {'print $2'} | sed 's/.$//' | sed 's/^.//'` 

#Get name from arp -a
name=`arp -a | grep $mac |  awk {'print $1'}`

#look into http://standards-oui.ieee.org/oui.txt and get manufacturer from first 3 bytes of mac-address
manu=`cat oui.txt | sed s/\-/:/g | grep -i ${mac::-9} | sed 's/^..................//'` #there might be a better solution ;-)

# Show gathered information
echo -e "\nNew node found:\n"
echo -e "IP: $ip"
echo -e "MAC-Address: $mac"
echo -e "DNS-Name: $name"
echo -e "Manufacturer: $manu\n" 

# Delete mac.tmp
rm mac.tmp

# Infinite loop ends here ---
#done
